### ISSUE TITLE
Port to Edge

### ISSUE THREAD

**Issue by timbru31** [timbru31/quickjira#11]
References:

* https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/extension-api-roadmap/
* https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/supported-apis/
* https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/porting-chrome-extensions/

**Comment by timbru31** [comment]
Current bugs:

* [ ] no omnibox
* [ ] only local storage, no sync

**Comment by timbru31** [comment]
Edge is currently not accepting submissions, see http://stackoverflow.com/a/38819741/1902598

**Comment by timbru31** [comment]
Submissions should be possible by now.

**Comment by timbru31** [comment]
Registration fee is for a developer account is EUR 14 (one time) 👎

**Comment by timbru31** [comment]
Status of submissions (May 2018)

>I have an extension ready for Edge. How can I get it submitted to the store?

>For the Windows 10 Anniversary Update, we are intentionally starting with a small set of extensions. The list of extensions is locked - you can see the list at our extensions page here. We want to be mindful about what extensions are available on the platform and watch for telemetry and feedback and make sure the reliability, performance and functionality of the browser isn’t impacted by these new features. Extension developers can submit a request to https://aka.ms/extension-request to be considered for a future update.

**Comment by timbru31** [comment]
Storage (sync) is now listed as a supported API of edge

**Comment by timbru31** [comment]
Todo: Test the new Chromium powered Edge. Did things change? Is the MS Store still a thing?

**Comment by timbru31** [comment]
Submission has been sent via the form.

**Comment by timbru31** [comment]
Submission has been approved, I can now submit it. (or work on #37 😅 )

**Comment by WesFrench** [comment]
I have been using this in Edge for a while, so thank you for that. Are the hotkeys and url still being worked on?

**Comment by timbru31** [comment]
Kinda. This issue was before Edge became a Chromium based browser.  
Normally everything should work fine and publishing it to the other store is just for convivence.

**Comment by filipesantosind** [comment]
Hello. Quick Jira is avaliable in the Microsoft Edge Add-ons? I can't find it to install on Edge.

**Comment by timbru31** [comment]
Submission is pending review 👏

**Comment by timbru31** [comment]
The extension is now live: https://microsoftedge.microsoft.com/addons/detail/oihenofhenonlmnogpbelbpnigeligfh
