### ISSUE TITLE
JIRA base URL can't be saved

### ISSUE THREAD

**Issue by winter2k** [timbru31/quickjira#15]
I tried to save the JIRA base URL like below:
https://greenhopper.app.xxxxxx.com/secure/QuickSearch.jspa?searchString=
I click "save options" button and it said "options were saved", however when I try to type in a jira id like "xxx-1234", it jump to this setting page again and there's an empty string there...

I tried both latest FF & FF ESR 52.2.1, with same result. Quick JIRA 0.9.1

**Comment by timbru31** [comment]
Hi @winter2k,

thanks for the error report. Weirdly enough it works for me, even with your anonymized URL.
Can you give me more details?

* What's your OS
* What's your exact Firefox version?
* (Please note that ESR releases are unsupported due to lack of new features required for WebExtensions)

**Comment by winter2k** [comment]
Thanks for your reply:)

    What's your OS
-- Windows 7 Professional
    What's your exact Firefox version?
-- Firefox ESR 52.2.1 (32bit), & Firefox 54.x (I don't remember the exact 54.x version, but should be the latest FF from firefox.com)
    (Please note that ESR releases are unsupported due to lack of new features required for WebExtensions)
-- that's ok, I'm guessing maybe FF doesn't work due to I'm using a chinese verision, I'll try English version later.

**Comment by winter2k** [comment]
Confirmed the issue is linked to Chinese version FF. I downloaded a English version FF, and it works now, thanks for your support anyway!

**Comment by timbru31** [comment]
Thanks for letting me know. I'll check out a Chinese version and debug the issue 👍

**Comment by winter2k** [comment]
Most probably it's related to different character coding, asc/utf-8/GB2312, etc. if you have time you can have a try but I guess Chinese language may block you:) I can use English FF anyway.

**Comment by timbru31** [comment]
@winter2k I've tried to reproduce your issue, but was unable to do so (even with Chinese FF) - feel free to try it again with v0.10.0 and a newer FF release. If the issues persists, I'll re-open this ticket.
