### ISSUE TITLE
Can not select Default Action in dropdown on the extension setup

### ISSUE THREAD

**Issue by Soccertanker** [timbru31/quickjira#221]
![QuickJira_DefaultAction](https://user-images.githubusercontent.com/28209982/70748215-6b7ea200-1cde-11ea-86f0-59de338a41dc.png)
I am unable to change the selection from "current tab" to another option.
This is what the screen looks like after I click "current tab" in attempt to change the option.
![QuickJira_DefaultAction_Issue](https://user-images.githubusercontent.com/28209982/70748321-aa145c80-1cde-11ea-9609-4eb5738d94f3.png)

Thank you,
Eric

**Comment by timbru31** [comment]
What browser are you using? :)

**Comment by Soccertanker** [comment]
Chrome 79. The drop-down works now. I did not change anything on my end other than rebooting a few times over the last week.

**Comment by timbru31** [comment]
Glad the system/extension/whatever self healed!
