### ISSUE TITLE
No option to disable omnibox search in Firefox Quantum

### ISSUE THREAD

**Issue by benfreke** [timbru31/quickjira#31]
Hi

I find the option to rapidly open the ticket really useful. But not being able to disable the option when typing in the omnibox is incredibly frustrating when I'm configuring JIRA and trying to search for help i.e. "jira add field to issue screen". 

Can this option be made configurable please? I'm ok if it can't be to ensure the plugin continues to work, it's just an annoyance in the way I personally work. I can definitely see how it is useful

**Comment by timbru31** [comment]
Hi @benfreke 👋,

sorry for my late response.
Sadly there is no way to disable or configure this option, see https://github.com/timbru31/quickjira/issues/9#issuecomment-340852297

Omnibox v2 is tracked here (#19), in case the API situation changes.
