### ISSUE TITLE
What's this and how to configure it?

### ISSUE THREAD

**Issue by lpoblet** [timbru31/quickjira#35]
![image](https://user-images.githubusercontent.com/1879045/46911354-96277a80-cfb5-11e8-9c6e-251e06665893.png)

When I type 'jira ' (that's jira + space) it appears this 'quiji |' and then I can enter the jira ID I'm after. Can I disable it or configure it to say something more meaningful?

**Comment by timbru31** [comment]
This is the “Omnibox Feature”.
Sadly you can’t configure it (see https://github.com/timbru31/quickjira/issues/9#issuecomment-340852297)

Nevertheless this request is tracked in #9
