### ISSUE TITLE
Url not considered valid

### ISSUE THREAD

**Issue by epam-ocherniavskaia** [timbru31/quickjira#367]
On my project, we use URL like this: http://srv-jira:8080, it is not considered valid by the tool. So I unable to specify default url for quick search as http://srv-jira:8080/issues/?jql= or for tickets

**Comment by timbru31** [comment]
Thanks, I'll take a look. Is `srv-jira` a placholder or the actual domain that's resolved in your internal network?

**Comment by epam-ocherniavskaia** [comment]
It is an actual url
