### ISSUE TITLE
Omnibox command: jira is not working

### ISSUE THREAD

**Issue by fubha** [timbru31/quickjira#397]
I am using chrome version `88.0.4324.150` and when i type in `jira` in the browser's tab, it doesn't trigger `quiji` mode like it used to before, and hence unable to open the jira ticket right away. Is something changed recently related to this?

**Comment by fubha** [comment]
![image](https://user-images.githubusercontent.com/14972419/108042112-364bad80-7061-11eb-95da-cbc85c158b69.png)

**Comment by timbru31** [comment]
Nothing changed on my end, I will take a look.

**Comment by petrvanek221** [comment]
Hi, facing the same issue as @fubha has described. Just typing jira will not trigger the quiji :(

**Comment by timbru31** [comment]
Works fine for me, you just need to hit the tab key.
