### ISSUE TITLE
Option to change search engine keyword/omnikeyword

### ISSUE THREAD

**Issue by mikky-cecil** [timbru31/quickjira#445]
**Feature idea:** I'd love to be able to change the "quiji" keyword, for example I'd probably change it to "quiji" instead of "jira".

I often Google my JIRA questions, so I'll go to the URL bar and start typing something like "jira notification settings", but then it ends up searching JIRA instead of Google. I work around this by not using jira as the first word OR back-spacing after typing "jira," but I wish I could just change it so I can use it more intentionally.

Thank you for an awesome plugin!

**Comment by timbru31** [comment]
Hi,

AFAIK it's (sadly) not possible to change they keyword to a user specified one. I'm tracking everything about the Omnibox here: #19

**Comment by mikky-cecil** [comment]
Oh I see, how bizarre! Thanks for pointing me towards the relevant ticket 👍
