### ISSUE TITLE
Options dialog not opening in Chrome

### ISSUE THREAD

**Issue by spfeiffer** [timbru31/quickjira#634]
Quickjira Version: 0.11.2
Chrome Version: Version 102.0.5005.63 (Official Build) (64-bit) on WIndows 10

When trying to configure the plugin nothing is happening when clicking the "Extension options" button. 

The following error is being shown in console: 
![image](https://user-images.githubusercontent.com/1539804/172700162-9305bae9-78a4-4b2b-9a90-c828bbd202b6.png)

Which points to the following code: 
![image](https://user-images.githubusercontent.com/1539804/172700286-12832315-683d-48eb-91a5-20efc8d346f3.png)

**Comment by timbru31** [comment]
Thanks, will take a look

**Comment by timbru31** [comment]
Closing because options page will move to a dedicated pages with Manifest v3
