### ISSUE TITLE
Please restore functionality of keeping spaces in searches or add an option to turn this functionality back on

### ISSUE THREAD

**Issue by lcooper12345** [timbru31/quickjira#85]
I was using this tool to search by keywords as often as card #'s but with the new update now I have to re-add spaces in Jira after I've searched This has greatly reduced the usefulness of the tool. Please re-add this ability if you can! :(

**Comment by timbru31** [comment]
Hi @lcooper12345,

I'll release a fix later today, sorry for the inconvenience!
