### ISSUE TITLE
Add shortcuts (default) to options page

### ISSUE THREAD

**Issue by timbru31** [timbru31/quickjira#9]
The list of default shortcut should be shown on the options page.

**Comment by timbru31** [comment]
Additionally examine if it's possible to grab the current assigned keyboard shortcut programatically.

**Comment by timbru31** [comment]
Localization strings are still todo

**Comment by wedi** [comment]
Does this issue include the request to add an option to change the search keyword?
I am frequently searching for jira related things on google and redirecting "jira" is not the best thing for me.
In addition, I prefer shorter keywords.

**Comment by timbru31** [comment]
No sadly the registered keyword for the omnibox can't be changed by the user AFAIK - A feature I'm looking for, too.
Thanks for the feedback, I'll consider re-thinking the keyword.

**Comment by wedi** [comment]
Thanks for coming back to me. Maybe you could add an option whether to register the search provider at all? Then I'd just deactivate it and add my own variant with the keyword of my choice.

**Comment by timbru31** [comment]
Currently I have to specify the desired omnibox keyword in the manifest.json which I can't change at runtime. I'm creating an issue for this and investigate further if there are plans from Google or Mozilla to support changes to this feature at runtime.

-----
Localizations have landed in 1fd9332dc40f5bf94ea94d0f37b5461f9cb2f693
